# Form implementation generated from reading ui file 'addui.ui'
#
# Created by: PyQt6 UI code generator 6.8.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(356, 332)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        Form.setMinimumSize(QtCore.QSize(356, 332))
        Form.setMaximumSize(QtCore.QSize(356, 559))
        Form.setStyleSheet("background-color: #E3E8E3;")
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.label_3 = QtWidgets.QLabel(parent=Form)
        self.label_3.setMaximumSize(QtCore.QSize(30, 30))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(5)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color: #043927;")
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap("s icon.png"))
        self.label_3.setScaledContents(True)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 0, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(parent=Form)
        self.label_2.setMaximumSize(QtCore.QSize(275, 50))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: #043927; font-weight: bold;")
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 1, 1, 2)
        self.line = QtWidgets.QFrame(parent=Form)
        self.line.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line.setObjectName("line")
        self.gridLayout.addWidget(self.line, 1, 2, 1, 1)
        self.frame = QtWidgets.QFrame(parent=Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setMinimumSize(QtCore.QSize(120, 500))
        self.frame.setMaximumSize(QtCore.QSize(150, 16777215))
        self.frame.setSizeIncrement(QtCore.QSize(10, 0))
        self.frame.setStyleSheet("background-color: #043927; border-top-right-radius: 15px;")
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.widget = QtWidgets.QWidget(parent=self.frame)
        self.widget.setGeometry(QtCore.QRect(20, 20, 85, 211))
        self.widget.setObjectName("widget")

        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")

        self.label_4 = QtWidgets.QLabel(parent=self.widget)
        self.label_4.setMaximumSize(QtCore.QSize(275, 50))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color: white; font-weight: bold")
        self.label_4.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4)
        self.label_5 = QtWidgets.QLabel(parent=self.widget)
        self.label_5.setMaximumSize(QtCore.QSize(275, 50))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("color: white; font-weight: bold")
        self.label_5.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.verticalLayout.addWidget(self.label_5)
        self.label_6 = QtWidgets.QLabel(parent=self.widget)
        self.label_6.setMaximumSize(QtCore.QSize(275, 50))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("color: white;font-weight: bold")
        self.label_6.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.verticalLayout.addWidget(self.label_6)
        self.label_7 = QtWidgets.QLabel(parent=self.widget)
        self.label_7.setMaximumSize(QtCore.QSize(275, 50))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("color: white;font-weight: bold")
        self.label_7.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.verticalLayout.addWidget(self.label_7)
        self.label_8 = QtWidgets.QLabel(parent=self.widget)
        self.label_8.setMaximumSize(QtCore.QSize(275, 50))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setStyleSheet("color: white;font-weight: bold")
        self.label_8.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.verticalLayout.addWidget(self.label_8)
        self.label_16 = QtWidgets.QLabel(parent=self.widget)
        self.label_16.setMaximumSize(QtCore.QSize(275, 50))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.label_16.setFont(font)
        self.label_16.setStyleSheet("color: white;font-weight: bold")
        self.label_16.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_16.setObjectName("label_16")
        self.verticalLayout.addWidget(self.label_16)
        self.label_9 = QtWidgets.QLabel(parent=self.widget)
        self.label_9.setMaximumSize(QtCore.QSize(275, 50))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setStyleSheet("color: white;font-weight: bold")
        self.label_9.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.verticalLayout.addWidget(self.label_9)
        self.gridLayout.addWidget(self.frame, 2, 0, 2, 2)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(20, 15, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        self.verticalLayout_2.addItem(spacerItem)
        self.lineEdit = QtWidgets.QLineEdit(parent=Form)
        self.lineEdit.setStyleSheet("border: 1px solid #043927; color: #043927;")
        self.lineEdit.setObjectName("lineEdit")
        self.verticalLayout_2.addWidget(self.lineEdit)
        self.lineEdit_2 = QtWidgets.QLineEdit(parent=Form)
        self.lineEdit_2.setStyleSheet("border: 1px solid #043927;color: #043927;")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.verticalLayout_2.addWidget(self.lineEdit_2)
        self.lineEdit_3 = QtWidgets.QLineEdit(parent=Form)
        self.lineEdit_3.setStyleSheet("border: 1px solid #043927;color: #043927;")
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.verticalLayout_2.addWidget(self.lineEdit_3)
        
        self.comboBox = QtWidgets.QComboBox(parent=Form)
        self.comboBox.setStyleSheet("""
                QComboBox {
                color: #043927;
                border: 1px solid #043927;
                } 
                QComboBox QAbstractItemView {
                background-color: #043927; 
                border: 1px solid white;
                selection-background-color: #065c45; /* Highlighted item */
                selection-color: white;
                padding: 5px;    
                }
        """)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItems(["","1", "2", "3", "4", "5", "6", "7"])

        self.verticalLayout_2.addWidget(self.comboBox)
        self.comboBox_2 = QtWidgets.QComboBox(parent=Form)
        self.comboBox_2.setStyleSheet("""
                QComboBox {
                color: #043927;
                border: 1px solid #043927;
                } 
                QComboBox QAbstractItemView {
                background-color: #043927; 
                border: 1px solid white;
                selection-background-color: #065c45; /* Highlighted item */
                selection-color: white;
                padding: 5px;    
                }
        """)
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItems(["", "Male", "Female"])
        self.verticalLayout_2.addWidget(self.comboBox_2)
        self.comboBox_3 = QtWidgets.QComboBox(parent=Form)
        self.comboBox_3.setStyleSheet("""
                QComboBox {
                color: #043927;
                border: 1px solid #043927;
                } 
                QComboBox QAbstractItemView {
                background-color: #043927; 
                border: 1px solid white;
                selection-background-color: #065c45; /* Highlighted item */
                selection-color: white;
                padding: 5px;    
                }
        """)
        self.comboBox_3.setObjectName("comboBox_3")
        self.comboBox_3.addItems([""])
        self.verticalLayout_2.addWidget(self.comboBox_3)
        self.comboBox_4 = QtWidgets.QComboBox(parent=Form)
        self.comboBox_4.setStyleSheet("""
                QComboBox {
                color: #043927;
                border: 1px solid #043927;
                } 
                QComboBox QAbstractItemView {
                background-color: #043927; 
                border: 1px solid white;
                selection-background-color: #065c45; /* Highlighted item */
                selection-color: white;
                padding: 5px;    
                }
        """)
        self.comboBox_4.setObjectName("comboBox_4")
        self.comboBox_4.addItems([""])
        self.verticalLayout_2.addWidget(self.comboBox_4)
        self.pushButton = QtWidgets.QPushButton(parent=Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton.sizePolicy().hasHeightForWidth())
        self.pushButton.setSizePolicy(sizePolicy)
        self.pushButton.setMaximumSize(QtCore.QSize(45, 20))
        self.pushButton.setStyleSheet("QPushButton{\n"
"background-color: #043927;\n"
"color: white; font-size: 10px\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"border-bottom: 2px solid white; border: 1px;\n"
"font-weight: bold;\n"
"}")
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout_2.addWidget(self.pushButton, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.gridLayout.addLayout(self.verticalLayout_2, 2, 2, 2, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_2.setText(_translate("Form", "Student Information System"))
        self.label_4.setText(_translate("Form", "First Name"))
        self.label_5.setText(_translate("Form", "Last Name"))
        self.label_6.setText(_translate("Form", "ID Number"))
        self.label_7.setText(_translate("Form", "Year Level"))
        self.label_8.setText(_translate("Form", "Gender"))
        self.label_16.setText(_translate("Form", "College Code"))
        self.label_9.setText(_translate("Form", "Program Name"))
        self.pushButton.setText(_translate("Form", "Save"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec())