# Form implementation generated from reading ui file 'studentwindow_ui.ui'
#
# Created by: PyQt6 UI code generator 6.8.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1100, 666)
        MainWindow.setMinimumSize(1100, 666)
        MainWindow.setStyleSheet("background-color: #E3E8E3;")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.tabWidget = QtWidgets.QTabWidget(parent=self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.tabWidget.setStyleSheet("""
    QTabBar::tab {
        color: white; /* Text color */
        background-color: #043927; /* Background color of the tab */
        padding: 10px; /* Padding around the text */
        border: 1px solid #065c45; /* Border around the tab */
        border-top-left-radius: 5px; /* Rounded corners */
        border-top-right-radius: 5px;s
    }

    QTabBar::tab:selected {
        color: #043927; /* Text color when selected */
        background-color: white; /* Background color when selected */
        border-bottom-color: white; /* Remove the bottom border when selected */
    }

    QTabBar::tab:hover {
        background-color: #065c45; /* Background color on hover */
    }
""")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout = QtWidgets.QGridLayout(self.tab)
        self.gridLayout.setObjectName("gridLayout")
        self.frame_2 = QtWidgets.QFrame(parent=self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_2.sizePolicy().hasHeightForWidth())
        self.frame_2.setSizePolicy(sizePolicy)
        self.frame_2.setMinimumSize(QtCore.QSize(0, 70))
        self.frame_2.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(11, 20, QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.label = QtWidgets.QLabel(parent=self.frame_2)
        self.label.setMaximumSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(5)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("color: #043927;")
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("s icon.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.label_2 = QtWidgets.QLabel(parent=self.frame_2)
        self.label_2.setMaximumSize(QtCore.QSize(275, 50))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: #043927;font-weight: bold;")
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.lineEdit = QtWidgets.QLineEdit(parent=self.frame_2)
        self.lineEdit.setStyleSheet("border: 1px solid #043927; color: #043927")
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout.addWidget(self.lineEdit)
        self.comboBox = QtWidgets.QComboBox(parent=self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox.sizePolicy().hasHeightForWidth())
        self.comboBox.setSizePolicy(sizePolicy)
        self.comboBox.setMinimumSize(QtCore.QSize(40, 0))
        self.comboBox.setStyleSheet("""
                QComboBox {
                background-color: #043927;
                color: white;
                } 
                QComboBox QAbstractItemView {
                background-color: #043927; 
                border: 1px solid white;
                selection-background-color: #065c45; /* Highlighted item */
                selection-color: white;
                padding: 5px;    
                }
        """)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.horizontalLayout.addWidget(self.comboBox)
        spacerItem2 = QtWidgets.QSpacerItem(5, 20, QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.horizontalLayout_4.addLayout(self.horizontalLayout)
        self.gridLayout.addWidget(self.frame_2, 0, 0, 1, 4)
        self.line = QtWidgets.QFrame(parent=self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line.sizePolicy().hasHeightForWidth())
        self.line.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.line.setFont(font)
        self.line.setLineWidth(1)
        self.line.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line.setObjectName("line")
        self.gridLayout.addWidget(self.line, 1, 2, 1, 1)
        self.frame = QtWidgets.QFrame(parent=self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setMinimumSize(QtCore.QSize(120, 500))
        self.frame.setMaximumSize(QtCore.QSize(150, 16777215))
        self.frame.setSizeIncrement(QtCore.QSize(10, 0))
        self.frame.setStyleSheet("background-color: #043927; border-top-right-radius: 15px;")
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.layoutWidget = QtWidgets.QWidget(parent=self.frame)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 10, 101, 131))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.pushButton_2 = QtWidgets.QPushButton(parent=self.layoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet("QPushButton{\n"
"color: white;\n"
"border-bottom: 2px solid white; font-weight: bold;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"border-bottom: 2px solid white;\n"
"}")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("students icon.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton_2.setIcon(icon)
        self.pushButton_2.setObjectName("pushButton_2")
        self.verticalLayout.addWidget(self.pushButton_2, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.pushButton_3 = QtWidgets.QPushButton(parent=self.layoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setStyleSheet("QPushButton{\n"
"color: white;font-weight: bold;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"border-bottom: 2px solid white;\n"
"}")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("badge_52dp_WHITE_FILL0_wght700_GRAD0_opsz48.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton_3.setIcon(icon1)
        self.pushButton_3.setObjectName("pushButton_3")
        self.verticalLayout.addWidget(self.pushButton_3, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.pushButton_4 = QtWidgets.QPushButton(parent=self.layoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setStyleSheet("QPushButton{\n"
"color: white;font-weight: bold;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"border-bottom: 2px solid white;\n"
"}")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("college icon.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton_4.setIcon(icon2)
        self.pushButton_4.setObjectName("pushButton_4")
        self.verticalLayout.addWidget(self.pushButton_4, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.gridLayout.addWidget(self.frame, 2, 0, 4, 1)
        spacerItem3 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        self.gridLayout.addItem(spacerItem3, 2, 2, 1, 1)
        
        #add
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pushButton = QtWidgets.QPushButton(parent=self.tab)
        self.pushButton.setStyleSheet("QPushButton{\n"
"background-color: #043927;\n"
"color: white;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"border-bottom: 2px solid white; border: 1px;\n"
"font-weight: bold;\n"
"}")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("add button white.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton.setIcon(icon3)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_2.addWidget(self.pushButton)
        self.comboBox_2 = QtWidgets.QComboBox(parent=self.tab)
        self.comboBox_2.setStyleSheet("""
                QComboBox {
                background-color: #043927;
                color: white;
                } 
                QComboBox QAbstractItemView {
                background-color: #043927; 
                border: 1px solid white;
                selection-background-color: #065c45; /* Highlighted item */
                selection-color: white;
                padding: 5px;    
                }
        """)
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.horizontalLayout_2.addWidget(self.comboBox_2)
        self.comboBox_3 = QtWidgets.QComboBox(parent=self.tab)
        self.comboBox_3.setStyleSheet("""
                QComboBox {
                background-color: #043927;
                color: white;
                } 
                QComboBox QAbstractItemView {
                background-color: #043927; 
                border: 1px solid white;
                selection-background-color: #065c45; /* Highlighted item */
                selection-color: white;
                padding: 5px;    
                }
        """)
        self.comboBox_3.setObjectName("comboBox_3")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.horizontalLayout_2.addWidget(self.comboBox_3)
        spacerItem4 = QtWidgets.QSpacerItem(70, 20, QtWidgets.QSizePolicy.Policy.MinimumExpanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem4)
        self.gridLayout.addLayout(self.horizontalLayout_2, 3, 2, 1, 2)
        spacerItem5 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout.addItem(spacerItem5, 4, 1, 1, 1)
        
        #tablewidget1
        self.tableWidget = QtWidgets.QTableWidget(parent=self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableWidget.sizePolicy().hasHeightForWidth())
        self.tableWidget.setSizePolicy(sizePolicy)
        self.tableWidget.setMinimumSize(QtCore.QSize(650, 200))
        #TableWidget
        self.tableWidget.setStyleSheet("""
QTableWidget {
    background-color: transparent;
    color: #043927;
}
QHeaderView::section {
    background-color: #043927;
    color: white;
    padding: 5px;
    font-weight: bold;
}
""")
        self.tableWidget.setLineWidth(1)
        self.tableWidget.setRowCount(0)
        self.tableWidget.setColumnCount(8)
        self.tableWidget.setHorizontalHeaderLabels(["ID Number", "First Name", "Last Name", "Year Level", "Gender", "Program Code", "College Code", "Actions"])
        self.tableWidget.horizontalHeader().setVisible(True)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.horizontalHeader().setSectionResizeMode(QtWidgets.QHeaderView.ResizeMode.Stretch)
        self.gridLayout.addWidget(self.tableWidget, 4, 2, 1, 1)

        spacerItem6 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Preferred)
        self.gridLayout.addItem(spacerItem6, 5, 3, 1, 1)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.tab_2)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.frame_3 = QtWidgets.QFrame(parent=self.tab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_3.sizePolicy().hasHeightForWidth())
        self.frame_3.setSizePolicy(sizePolicy)
        self.frame_3.setMinimumSize(QtCore.QSize(0, 70))
        self.frame_3.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        spacerItem7 = QtWidgets.QSpacerItem(11, 20, QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem7)
        self.label_3 = QtWidgets.QLabel(parent=self.frame_3)
        self.label_3.setMaximumSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(5)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color: #043927;")
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap("s icon.png"))
        self.label_3.setScaledContents(True)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_6.addWidget(self.label_3)
        self.label_4 = QtWidgets.QLabel(parent=self.frame_3)
        self.label_4.setMaximumSize(QtCore.QSize(275, 50))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color: #043927;font-weight: bold;")
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_6.addWidget(self.label_4)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem8)
        self.lineEdit_2 = QtWidgets.QLineEdit(parent=self.frame_3)
        self.lineEdit_2.setStyleSheet("border: 1px solid #043927;color: #043927;")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.horizontalLayout_6.addWidget(self.lineEdit_2)
        self.comboBox_6 = QtWidgets.QComboBox(parent=self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_6.sizePolicy().hasHeightForWidth())
        self.comboBox_6.setSizePolicy(sizePolicy)
        self.comboBox_6.setMinimumSize(QtCore.QSize(40, 0))
        self.comboBox_6.setStyleSheet("""
                QComboBox {
                background-color: #043927;
                color: white;
                } 
                QComboBox QAbstractItemView {
                background-color: #043927; 
                border: 1px solid white;
                selection-background-color: #065c45; /* Highlighted item */
                selection-color: white;
                padding: 5px;    
                }
        """)
        self.comboBox_6.setObjectName("comboBox_6")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.horizontalLayout_6.addWidget(self.comboBox_6)
        spacerItem9 = QtWidgets.QSpacerItem(5, 20, QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem9)
        self.horizontalLayout_5.addLayout(self.horizontalLayout_6)
        self.gridLayout_3.addWidget(self.frame_3, 0, 0, 1, 4)
        self.line_2 = QtWidgets.QFrame(parent=self.tab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line_2.sizePolicy().hasHeightForWidth())
        self.line_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.line_2.setFont(font)
        self.line_2.setLineWidth(1)
        self.line_2.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_2.setObjectName("line_2")
        self.gridLayout_3.addWidget(self.line_2, 1, 2, 1, 1)
        self.frame_4 = QtWidgets.QFrame(parent=self.tab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_4.sizePolicy().hasHeightForWidth())
        self.frame_4.setSizePolicy(sizePolicy)
        self.frame_4.setMinimumSize(QtCore.QSize(120, 500))
        self.frame_4.setMaximumSize(QtCore.QSize(150, 16777215))
        self.frame_4.setSizeIncrement(QtCore.QSize(10, 0))
        self.frame_4.setStyleSheet("background-color: #043927; border-top-right-radius: 15px;")
        self.frame_4.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_4.setObjectName("frame_4")
        self.layoutWidget_2 = QtWidgets.QWidget(parent=self.frame_4)
        self.layoutWidget_2.setGeometry(QtCore.QRect(10, 10, 101, 131))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.pushButton_5 = QtWidgets.QPushButton(parent=self.layoutWidget_2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_5.setFont(font)
        self.pushButton_5.setStyleSheet("QPushButton{\n"
"color: white;font-weight: bold;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"border-bottom: 2px solid white;\n"
"}")
        self.pushButton_5.setIcon(icon)
        self.pushButton_5.setObjectName("pushButton_5")
        self.verticalLayout_2.addWidget(self.pushButton_5, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.pushButton_6 = QtWidgets.QPushButton(parent=self.layoutWidget_2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_6.setFont(font)
        self.pushButton_6.setStyleSheet("QPushButton{\n"
"color: white;font-weight: bold;\n"
"border-bottom: 2px solid white;\n"
"}\n"
"")
        self.pushButton_6.setIcon(icon1)
        self.pushButton_6.setObjectName("pushButton_6")
        self.verticalLayout_2.addWidget(self.pushButton_6, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.pushButton_7 = QtWidgets.QPushButton(parent=self.layoutWidget_2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_7.setFont(font)
        self.pushButton_7.setStyleSheet("QPushButton{\n"
"color: white;font-weight: bold;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"border-bottom: 2px solid white;\n"
"}")
        self.pushButton_7.setIcon(icon2)
        self.pushButton_7.setObjectName("pushButton_7")
        self.verticalLayout_2.addWidget(self.pushButton_7, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.gridLayout_3.addWidget(self.frame_4, 2, 0, 4, 1)
        spacerItem10 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        self.gridLayout_3.addItem(spacerItem10, 2, 2, 1, 1)
        
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.pushButton_11 = QtWidgets.QPushButton(parent=self.tab_2)
        self.pushButton_11.setStyleSheet("QPushButton{\n"
"background-color: #043927;\n"
"color: white;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"border-bottom: 2px solid white; border: 1px;\n"
"font-weight: bold;\n"
"}")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("add button white.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton_11.setIcon(icon4)
        self.pushButton_11.setObjectName("pushButton_11")
        self.horizontalLayout_3.addWidget(self.pushButton_11)
        self.comboBox_4 = QtWidgets.QComboBox(parent=self.tab_2)
        self.comboBox_4.setStyleSheet("""
                QComboBox {
                background-color: #043927;
                color: white;
                } 
                QComboBox QAbstractItemView {
                background-color: #043927; 
                border: 1px solid white;
                selection-background-color: #065c45; /* Highlighted item */
                selection-color: white;
                padding: 5px;    
                }
        """)
        self.comboBox_4.setObjectName("comboBox_4")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.horizontalLayout_3.addWidget(self.comboBox_4)
        self.comboBox_5 = QtWidgets.QComboBox(parent=self.tab_2)
        self.comboBox_5.setStyleSheet("""
                QComboBox {
                background-color: #043927;
                color: white;
                } 
                QComboBox QAbstractItemView {
                background-color: #043927; 
                border: 1px solid white;
                selection-background-color: #065c45; /* Highlighted item */
                selection-color: white;
                padding: 5px;    
                }
        """)
        self.comboBox_5.setObjectName("comboBox_5")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.horizontalLayout_3.addWidget(self.comboBox_5)
        spacerItem11 = QtWidgets.QSpacerItem(70, 20, QtWidgets.QSizePolicy.Policy.MinimumExpanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem11)
        self.gridLayout_3.addLayout(self.horizontalLayout_3, 3, 2, 1, 2)
        spacerItem12 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout_3.addItem(spacerItem12, 4, 1, 1, 1)
        
        #tablewidget2
        self.tableWidget_2 = QtWidgets.QTableWidget(parent=self.tab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableWidget_2.sizePolicy().hasHeightForWidth())
        self.tableWidget_2.setSizePolicy(sizePolicy)
        self.tableWidget_2.setMinimumSize(QtCore.QSize(650, 200))
        self.tableWidget_2.setStyleSheet("""
QTableWidget {
    background-color: transparent;
    color: #043927;
}
QHeaderView::section {
    background-color: #043927;
    color: white;
    padding: 5px;
    font-weight: bold;
}
""")
        self.tableWidget_2.setLineWidth(1)
        self.tableWidget_2.setRowCount(0)
        self.tableWidget_2.setColumnCount(0)
        self.tableWidget_2.setHorizontalHeaderLabels(["Program Code", "Program Name", "College Code"])
        self.tableWidget_2.horizontalHeader().setVisible(True)
        self.tableWidget_2.setObjectName("tableWidget_2")
        self.tableWidget_2.horizontalHeader().setSectionResizeMode(QtWidgets.QHeaderView.ResizeMode.Stretch)
        self.gridLayout_3.addWidget(self.tableWidget_2, 4, 2, 1, 1)


        spacerItem13 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Preferred)
        self.gridLayout_3.addItem(spacerItem13, 5, 3, 1, 1)
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")

        

        self.gridLayout_4 = QtWidgets.QGridLayout(self.tab_3)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.frame_6 = QtWidgets.QFrame(parent=self.tab_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_6.sizePolicy().hasHeightForWidth())
        self.frame_6.setSizePolicy(sizePolicy)
        self.frame_6.setMinimumSize(QtCore.QSize(0, 70))
        self.frame_6.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_6.setObjectName("frame_6")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.frame_6)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        spacerItem14 = QtWidgets.QSpacerItem(11, 20, QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem14)
        self.label_5 = QtWidgets.QLabel(parent=self.frame_6)
        self.label_5.setMaximumSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(5)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("color: #043927;")
        self.label_5.setText("")
        self.label_5.setPixmap(QtGui.QPixmap("s icon.png"))
        self.label_5.setScaledContents(True)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_9.addWidget(self.label_5)
        self.label_6 = QtWidgets.QLabel(parent=self.frame_6)
        self.label_6.setMaximumSize(QtCore.QSize(275, 50))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("color: #043927;font-weight: bold;")
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_9.addWidget(self.label_6)
        spacerItem15 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem15)
        self.lineEdit_3 = QtWidgets.QLineEdit(parent=self.frame_6)
        self.lineEdit_3.setStyleSheet("border: 1px solid #043927;color: #043927;")
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.horizontalLayout_9.addWidget(self.lineEdit_3)
        self.comboBox_9 = QtWidgets.QComboBox(parent=self.frame_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_9.sizePolicy().hasHeightForWidth())
        self.comboBox_9.setSizePolicy(sizePolicy)
        self.comboBox_9.setMinimumSize(QtCore.QSize(40, 0))
        self.comboBox_9.setStyleSheet("""
                QComboBox {
                background-color: #043927;
                color: white;
                } 
                QComboBox QAbstractItemView {
                background-color: #043927; 
                border: 1px solid white;
                selection-background-color: #065c45; /* Highlighted item */
                selection-color: white;
                padding: 5px;    
                }
        """)
        self.comboBox_9.setObjectName("comboBox_9")
        self.comboBox_9.addItem("")
        self.comboBox_9.addItem("")
        self.comboBox_9.addItem("")
        self.horizontalLayout_9.addWidget(self.comboBox_9)
        spacerItem16 = QtWidgets.QSpacerItem(5, 20, QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem16)
        self.horizontalLayout_8.addLayout(self.horizontalLayout_9)
        self.gridLayout_4.addWidget(self.frame_6, 0, 0, 1, 4)
        self.line_3 = QtWidgets.QFrame(parent=self.tab_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line_3.sizePolicy().hasHeightForWidth())
        self.line_3.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.line_3.setFont(font)
        self.line_3.setLineWidth(1)
        self.line_3.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_3.setObjectName("line_3")
        self.gridLayout_4.addWidget(self.line_3, 1, 2, 1, 1)
        self.frame_5 = QtWidgets.QFrame(parent=self.tab_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_5.sizePolicy().hasHeightForWidth())
        self.frame_5.setSizePolicy(sizePolicy)
        self.frame_5.setMinimumSize(QtCore.QSize(120, 500))
        self.frame_5.setMaximumSize(QtCore.QSize(150, 16777215))
        self.frame_5.setSizeIncrement(QtCore.QSize(10, 0))
        self.frame_5.setStyleSheet("background-color: #043927; border-top-right-radius: 15px;")
        self.frame_5.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_5.setObjectName("frame_5")
        self.layoutWidget_3 = QtWidgets.QWidget(parent=self.frame_5)
        self.layoutWidget_3.setGeometry(QtCore.QRect(10, 10, 101, 131))
        self.layoutWidget_3.setObjectName("layoutWidget_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.layoutWidget_3)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.pushButton_8 = QtWidgets.QPushButton(parent=self.layoutWidget_3)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_8.setFont(font)
        self.pushButton_8.setStyleSheet("QPushButton{\n"
"color: white;font-weight: bold;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"border-bottom: 2px solid white;\n"
"}")
        self.pushButton_8.setIcon(icon)
        self.pushButton_8.setObjectName("pushButton_8")
        self.verticalLayout_3.addWidget(self.pushButton_8, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.pushButton_9 = QtWidgets.QPushButton(parent=self.layoutWidget_3)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_9.setFont(font)
        self.pushButton_9.setStyleSheet("QPushButton{\n"
"color: white;font-weight: bold;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"border-bottom: 2px solid white;\n"
"}\n"
"")
        self.pushButton_9.setIcon(icon1)
        self.pushButton_9.setObjectName("pushButton_9")
        self.verticalLayout_3.addWidget(self.pushButton_9, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.pushButton_10 = QtWidgets.QPushButton(parent=self.layoutWidget_3)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_10.setFont(font)
        self.pushButton_10.setStyleSheet("QPushButton{\n"
"color: white;font-weight: bold;\n"
"border-bottom: 2px solid white;\n"
"}\n"
"\n"
"")
        self.pushButton_10.setIcon(icon2)
        self.pushButton_10.setObjectName("pushButton_10")
        self.verticalLayout_3.addWidget(self.pushButton_10, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.gridLayout_4.addWidget(self.frame_5, 2, 0, 4, 1)
        spacerItem17 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        self.gridLayout_4.addItem(spacerItem17, 2, 2, 1, 1)

        #add
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.pushButton_12 = QtWidgets.QPushButton(parent=self.tab_3)
        self.pushButton_12.setStyleSheet("QPushButton{\n"
"background-color: #043927;\n"
"color: white;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"border-bottom: 2px solid white; border: 1px;\n"
"font-weight: bold;\n"
"}")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("add button white.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton_12.setIcon(icon5)
        self.pushButton_12.setObjectName("pushButton_12")
        self.horizontalLayout_7.addWidget(self.pushButton_12)
        self.comboBox_7 = QtWidgets.QComboBox(parent=self.tab_3)
        self.comboBox_7.setStyleSheet("""
                QComboBox {
                background-color: #043927;
                color: white;
                } 
                QComboBox QAbstractItemView {
                background-color: #043927; 
                border: 1px solid white;
                selection-background-color: #065c45; /* Highlighted item */
                selection-color: white;
                padding: 5px;    
                }
        """)
        self.comboBox_7.setObjectName("comboBox_7")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.horizontalLayout_7.addWidget(self.comboBox_7)
        self.comboBox_8 = QtWidgets.QComboBox(parent=self.tab_3)
        self.comboBox_8.setStyleSheet("""
                QComboBox {
                background-color: #043927;
                color: white;
                } 
                QComboBox QAbstractItemView {
                background-color: #043927; 
                border: 1px solid white;
                selection-background-color: #065c45; /* Highlighted item */
                selection-color: white;
                padding: 5px;    
                }
        """)
        self.comboBox_8.setObjectName("comboBox_8")
        self.comboBox_8.addItem("")
        self.comboBox_8.addItem("")
        self.comboBox_8.addItem("")
        self.horizontalLayout_7.addWidget(self.comboBox_8)
        spacerItem18 = QtWidgets.QSpacerItem(70, 20, QtWidgets.QSizePolicy.Policy.MinimumExpanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem18)
        self.gridLayout_4.addLayout(self.horizontalLayout_7, 3, 2, 1, 2)
        spacerItem19 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout_4.addItem(spacerItem19, 4, 1, 1, 1)

        #tablewidget3
        self.tableWidget_3 = QtWidgets.QTableWidget(parent=self.tab_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableWidget_3.sizePolicy().hasHeightForWidth())
        self.tableWidget_3.setSizePolicy(sizePolicy)
        self.tableWidget_3.setMinimumSize(QtCore.QSize(650, 200))
        self.tableWidget_3.setStyleSheet("""
QTableWidget {
    background-color: transparent;
    color: #043927;
}
QHeaderView::section {
    background-color: #043927;
    color: white;
    padding: 5px;
    font-weight: bold;
}
""")
        self.tableWidget_3.setLineWidth(1)
        self.tableWidget_3.setRowCount(0)
        self.tableWidget_3.setColumnCount(0)
        self.tableWidget_3.setHorizontalHeaderLabels(["College Code", "College Name"])
        self.tableWidget_3.horizontalHeader().setVisible(True)
        self.tableWidget_3.setObjectName("tableWidget_3")
        self.tableWidget_3.horizontalHeader().setSectionResizeMode(QtWidgets.QHeaderView.ResizeMode.Stretch)
        self.gridLayout_4.addWidget(self.tableWidget_3, 4, 2, 1, 1)


        spacerItem20 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Preferred)
        self.gridLayout_4.addItem(spacerItem20, 5, 3, 1, 1)
        self.tabWidget.addTab(self.tab_3, "")
        
        self.gridLayout_2.addWidget(self.tabWidget, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 877, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.tabWidget.setCurrentIndex(0)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_2.setText(_translate("MainWindow", "Student Information System"))
        self.comboBox.setItemText(0, _translate("MainWindow", "Search By:"))
        self.comboBox.setItemText(1, _translate("MainWindow", "ID Number"))
        self.comboBox.setItemText(2, _translate("MainWindow", "First Name"))
        self.comboBox.setItemText(3, _translate("MainWindow", "Last Name"))
        self.comboBox.setItemText(4, _translate("MainWindow", "Year Level"))
        self.comboBox.setItemText(5, _translate("MainWindow", "Gender"))
        self.comboBox.setItemText(6, _translate("MainWindow", "Program Code"))
        self.comboBox.setItemText(7, _translate("MainWindow", "College Code"))
        self.pushButton_2.setText(_translate("MainWindow", "Students"))
        self.pushButton_3.setText(_translate("MainWindow", "Programs"))
        self.pushButton_4.setText(_translate("MainWindow", "Colleges"))
        self.pushButton.setText(_translate("MainWindow", "Add"))
        self.pushButton_11.setText(_translate("MainWindow", "Add"))
        self.pushButton_12.setText(_translate("MainWindow", "Add"))
        self.comboBox_2.setItemText(0, _translate("MainWindow", "Sort By:"))
        self.comboBox_2.setItemText(1, _translate("MainWindow", "ID Number"))
        self.comboBox_2.setItemText(2, _translate("MainWindow", "First Name"))
        self.comboBox_2.setItemText(3, _translate("MainWindow", "Last Name"))
        self.comboBox_2.setItemText(4, _translate("MainWindow", "Year Level"))
        self.comboBox_2.setItemText(5, _translate("MainWindow", "Gender"))
        self.comboBox_2.setItemText(6, _translate("MainWindow", "Program Code"))
        self.comboBox_2.setItemText(7, _translate("MainWindow", "College Code"))
        self.comboBox_3.setItemText(0, _translate("MainWindow", "Order:"))
        self.comboBox_3.setItemText(1, _translate("MainWindow", "Ascending"))
        self.comboBox_3.setItemText(2, _translate("MainWindow", "Descending"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Students"))
        self.label_4.setText(_translate("MainWindow", "Student Information System"))
        self.comboBox_6.setItemText(0, _translate("MainWindow", "Search By:"))
        self.comboBox_6.setItemText(1, _translate("MainWindow", "Program Code"))
        self.comboBox_6.setItemText(2, _translate("MainWindow", "Program Name"))
        self.comboBox_6.setItemText(3, _translate("MainWindow", "College Code"))
        self.pushButton_5.setText(_translate("MainWindow", "Students"))
        self.pushButton_6.setText(_translate("MainWindow", "Programs"))
        self.pushButton_7.setText(_translate("MainWindow", "Colleges"))
        self.comboBox_4.setItemText(0, _translate("MainWindow", "Sort By:"))
        self.comboBox_4.setItemText(1, _translate("MainWindow", "Program Code"))
        self.comboBox_4.setItemText(2, _translate("MainWindow", "Program Name"))
        self.comboBox_4.setItemText(3, _translate("MainWindow", "College Code"))
        self.comboBox_5.setItemText(0, _translate("MainWindow", "Order:"))
        self.comboBox_5.setItemText(1, _translate("MainWindow", "Ascending"))
        self.comboBox_5.setItemText(2, _translate("MainWindow", "Descending"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Programs"))
        self.label_6.setText(_translate("MainWindow", "Student Information System"))
        self.comboBox_9.setItemText(0, _translate("MainWindow", "Search By:"))
        self.comboBox_9.setItemText(1, _translate("MainWindow", "College Code"))
        self.comboBox_9.setItemText(2, _translate("MainWindow", "College Name"))
        self.pushButton_8.setText(_translate("MainWindow", "Students"))
        self.pushButton_9.setText(_translate("MainWindow", "Programs"))
        self.pushButton_10.setText(_translate("MainWindow", "Colleges"))
        self.comboBox_7.setItemText(0, _translate("MainWindow", "Sort By:"))
        self.comboBox_7.setItemText(1, _translate("MainWindow", "College Code"))
        self.comboBox_7.setItemText(2, _translate("MainWindow", "College Name"))
        self.comboBox_8.setItemText(0, _translate("MainWindow", "Order:"))
        self.comboBox_8.setItemText(1, _translate("MainWindow", "Ascending"))
        self.comboBox_8.setItemText(2, _translate("MainWindow", "Descending"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "Colleges"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
